services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: embarkx
      POSTGRES_PASSWORD: embarkx
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  config-server-ms:
    image: mwangialex26/config-server-ms:latest
    container_name: config-server-ms
    ports:
      - 8080:8080
    depends_on:
      - service-reg
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  service-reg:
    image: mwangialex26/service-reg:latest
    container_name: service-reg
    ports:
      - "8761:8761"
    depends_on:
      - rabbitmq
      - zipkin
      - postgres
      - pgadmin
    networks:
      - microservice-network
      - postgres

  companyms:
    image: mwangialex26/companyms:latest
    container_name: company
    ports:
      - "8081:8081"
    depends_on:
      - service-reg
      - config-server-ms
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  jobms:
    image: mwangialex26/jobms:latest
    container_name: job
    ports:
      - "8082:8082"
    depends_on:
      - service-reg
      - config-server-ms
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-reg:8761/eureka

  reviewms:
    image: mwangialex26/reviewms:latest
    container_name: review
    ports:
      - "8083:8083"
    depends_on:
      - service-reg
      - config-server-ms
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - microservice-network
      - postgres

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - microservice-network
      - postgres

  gateway-ms:
    container_name: gateway-ms
    image: mwangialex26/gateway-ms:latest
    ports:
      - 8084:8084
    depends_on:
      - service-reg
    networks:
      - microservice-network
      - postgres

networks:
  microservice-network:
    driver: bridge
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: